CREATE TABLE PMENOS_DESCONTO(
	ID_DESCONTO INT NOT NULL IDENTITY(1, 1),
	TIPO_DESCONTO VARCHAR(15) NOT NULL,
	XXXX_DH_ALT DATETIME DEFAULT GETDATE() NOT NULL,
	ID_CLIENTE INT NULL,
	CONSTRAINT DS_ID_DESCONTO_PK PRIMARY KEY (ID_DESCONTO),
	CONSTRAINT DS_CLIENTE_FK FOREIGN KEY (ID_CLIENTE) REFERENCES PMENOS_CLIENTE(ID_CLIENTE)
);