USE PMENOS_DESAFIO

CREATE TABLE PRODUTO_LOJA(
	ID_LOJA INT NOT NULL,
	ID_PRODUTO INT NOT NULL,
	CONSTRAINT PRODUTO_LOJA_PK PRIMARY KEY (ID_LOJA, ID_PRODUTO),
	CONSTRAINT FK_ID_LOJA FOREIGN KEY (ID_LOJA) REFERENCES PMENOS_LOJAS(ID_LOJA),
	CONSTRAINT FK_ID_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PMENOS_PRODUTOS(ID_PRODUTO)
);

