CREATE TABLE PMENOS_DESAFIO.dbo.PMENOS_PRODUTOS(
	ID_PRODUTO INT NOT NULL IDENTITY(1, 1),
	PRODUTO_DESCRICAO VARCHAR(50) NOT NULL,
	PRECO NUMERIC NULL,
	XXXX_DH_ALT DATETIME DEFAULT GETDATE() NOT NULL,
	CONSTRAINT PM_ID_PRODUTO_PK PRIMARY KEY (ID_PRODUTO)
)